"""Generate Markdown and PDF audit reports from stored policy data."""
from __future__ import annotations

from datetime import datetime
from typing import Any

from pymupdf import open as open_pdf

from app.services.audit_pipeline import _recommendation_headline, policy_to_response


def _safe_filename(name: str) -> str:
    base = name.rsplit(".", 1)[0] if name else "policy"
    cleaned = "".join(c if c.isalnum() or c in "._-" else "_" for c in base)
    return cleaned or "policy"


def build_markdown_report(policy: dict) -> str:
    data = policy_to_response(policy)
    metrics = data.get("metrics") or {}
    lines = [
        f"# Policy Audit Report: {data.get('filename', 'Policy')}",
        "",
        f"**Verdict:** {data.get('verdict_label') or 'REVIEW'}",
        f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Uploaded:** {data.get('uploaded_at', '—')}",
        "",
        "## Scorecard",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| PED waiting period | {metrics.get('ped_waiting_period_months', '—')} months |",
        f"| Room rent cap | {metrics.get('room_rent_cap', '—')} |",
        f"| Co-payment | {metrics.get('co_payment_percentage', '—')}% |",
        f"| Restoration benefit | {metrics.get('restoration_benefit', '—')} |",
        "",
    ]

    label = (data.get("verdict_label") or "REVIEW").upper()
    headline = data.get("recommendation_headline") or _recommendation_headline(label)
    summary = data.get("recommendation_summary") or ""
    strategic = data.get("strategic_verdict") or ""
    whats_missing = data.get("whats_missing") or ""
    profile = data.get("user_profile") or {}

    lines.extend([
        "## Auditor's Recommendation",
        "",
        f"**{headline}**",
        "",
    ])
    if profile:
        city = profile.get("policy_city") or profile.get("user_city") or "—"
        pin = profile.get("policy_pincode")
        room = profile.get("local_room_cost")
        si = profile.get("user_sum_insured")
        room_txt = f"₹{int(room):,}/day" if room is not None else "—"
        si_txt = f"₹{int(si):,}" if si is not None else "—"
        zone = profile.get("policy_zone") or "—"
        district = profile.get("policy_district")
        pin_part = f"Pincode {pin}" + (f" ({district})" if pin and district else "") if pin else ""
        context = " · ".join(
            part for part in (
                pin_part,
                f"{city} ({profile.get('city_tier', '—')})",
                f"Zone {zone}",
                f"Room benchmark {room_txt}",
                f"Sum insured {si_txt}",
            ) if part
        )
        lines.extend([
            f"**Policy context:** {context}",
            "",
        ])
    if summary:
        lines.extend(["**The Verdict:**", "", summary, ""])
    if whats_missing:
        lines.extend([
            "**Critical gaps:**",
            "",
            whats_missing,
            "",
        ])

    lines.extend([
        "## Strategic Verdict",
        "",
        strategic or data.get("verdict") or "No verdict available.",
        "",
    ])

    risks = data.get("key_risks") or []
    if risks:
        lines.append("## Key Risks")
        lines.append("")
        for risk in risks:
            lines.append(f"- {risk}")
        lines.append("")

    strengths = data.get("key_strengths") or []
    if strengths:
        lines.append("## Key Strengths")
        lines.append("")
        for strength in strengths:
            lines.append(f"- {strength}")
        lines.append("")

    lines.append("---")
    lines.append("*Report generated by TalkFlow Policy Evaluator*")
    return "\n".join(lines)


def build_pdf_report(policy: dict) -> bytes:
    data = policy_to_response(policy)
    metrics = data.get("metrics") or {}

    doc = open_pdf()
    page = doc.new_page(width=595, height=842)
    y = 50
    line_height = 14
    margin = 50
    max_width = 495

    def write_line(text: str, *, size: int = 11, gap: int = 4) -> None:
        nonlocal y, page
        if y > 780:
            page = doc.new_page(width=595, height=842)
            y = 50
        page.insert_text((margin, y), text[:120], fontsize=size)
        y += line_height + gap

    write_line("TalkFlow Policy Audit Report", size=16, gap=8)
    write_line(f"File: {data.get('filename', 'Policy')}", size=12)
    write_line(f"Verdict: {data.get('verdict_label') or 'REVIEW'}", size=12, gap=8)

    write_line("Scorecard", size=13, gap=6)
    write_line(f"PED waiting: {metrics.get('ped_waiting_period_months', '—')} months")
    write_line(f"Room rent cap: {metrics.get('room_rent_cap', '—')}")
    write_line(f"Co-payment: {metrics.get('co_payment_percentage', '—')}%")
    write_line(f"Restoration: {metrics.get('restoration_benefit', '—')}", gap=8)

    label = (data.get("verdict_label") or "REVIEW").upper()
    headline = data.get("recommendation_headline") or _recommendation_headline(label)
    summary = data.get("recommendation_summary") or ""
    strategic = data.get("strategic_verdict") or ""
    whats_missing = data.get("whats_missing") or ""
    profile = data.get("user_profile") or {}

    write_line("Auditor's Recommendation", size=13, gap=6)
    for chunk_start in range(0, len(headline), 90):
        write_line(headline[chunk_start : chunk_start + 90])
    if profile:
        city = profile.get("policy_city") or profile.get("user_city") or "—"
        pin = profile.get("policy_pincode")
        pin_txt = f" pincode {pin}" if pin else ""
        profile_line = f"Policy context:{pin_txt} {city} ({profile.get('city_tier', '—')})"
        write_line(profile_line, gap=2)
    if summary:
        write_line("The Verdict:", size=12, gap=4)
        for chunk_start in range(0, len(summary), 90):
            write_line(summary[chunk_start : chunk_start + 90], gap=2)
    if whats_missing:
        write_line("Critical gaps:", size=12, gap=4)
        for chunk_start in range(0, len(whats_missing), 90):
            write_line(whats_missing[chunk_start : chunk_start + 90], gap=2)

    write_line("Strategic Verdict", size=13, gap=6)
    verdict = strategic or data.get("verdict") or ""
    for chunk_start in range(0, len(verdict), 90):
        write_line(verdict[chunk_start : chunk_start + 90])

    risks = data.get("key_risks") or []
    if risks:
        write_line("Key Risks", size=13, gap=6)
        for risk in risks:
            for chunk_start in range(0, len(risk), 90):
                write_line(f"- {risk[chunk_start : chunk_start + 88]}")

    strengths = data.get("key_strengths") or []
    if strengths:
        write_line("Key Strengths", size=13, gap=6)
        for strength in strengths:
            for chunk_start in range(0, len(strength), 90):
                write_line(f"- {strength[chunk_start : chunk_start + 88]}")

    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


def report_attachment_name(policy: dict, fmt: str) -> str:
    base = _safe_filename(policy.get("filename") or "policy")
    ext = "pdf" if fmt == "pdf" else "md"
    return f"{base}_Audit_Report.{ext}"
